### ISSUE TITLE
Cannot Access libogg Project Properties Page in Visual Studio

### ISSUE THREAD

**Issue by jleveque** [AprilAndFriends/theoraplayer#2]
I saw the 1.1.0 build had been tagged, so I updated my source for the first time in a couple months. I'm now using VS2015, but I can imagine this problem exists for VS2013 users as well.

Upon upgrading the project from VS2013 to VS2015, I get this message in the log:

>Upgrading project 'libogg'...
The imported project "C:\theoraplayer-1.1.0\msvc\vs2013\props-generic\platform-Android.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\theoraplayer-1.1.0\ogg\msvc\vs2013\libogg.vcxproj

And then once the solution opens, I cannot access the libogg properties page in VS. When I try, I receive a messagebox that contiains the same error.

All the other projects seem fine; the problem seems isolated to the libogg project.

**Comment by kspes** [comment]
Hmm, yeah I'm in the process of updating libogg, vorbis and theora to the new build system but it seems to have problems if the user doesn't have android build scripts installed. which are obscure and not many companies use them though.

I had to pause my efforts on porting because my visual studio installation has gotten messed up and I'm on vacation with slow internet ;)


However, I have pushed the android props files blindly, give it a try, with some luck, it'll fix your problems.

in the near future we plan to upgrade to visual studio 2015 and separate the android build system by migrating to android studio since it finally supports c++ building

**Comment by jleveque** [comment]
Thanks - that did resolve the issue.

Funny you should mention it, I was actually attempting to muck around with the VS2015 built-in Android build system, myself. If I make any progess or hit any snags that you should know about, I'll let you know.

**Comment by kspes** [comment]
great, glad it's solved :)

PS: Don't do it, only pain and hardship await if you use android with visual studio :) It's possible, it works, but it sucks
