### ISSUE TITLE
Compiling for Android

### ISSUE THREAD

**Issue by machine-mind** [AprilAndFriends/theoraplayer#32]
Hi,
I would like to compile theoraplayer for android. Are there any examples of compiling and including it in a CMake based Android project?

**Comment by borisblizzard** [comment]
We have a setup through Visual Studio 2015 and MSBuild scripts that uses Android SDK and NDK to compile it, but there are some very specific steps that need to be done for the installation. We will, however, make it possible to compile everything through Android Studio in the coming weeks, maybe even during the course of the next week. So if you can wait that long, it would probably be the best option. :)

**Comment by machine-mind** [comment]
@borisblizzard This sounds great! Really looking forward to this! Thanks for all the effort you guys are putting into this project!

**Comment by machine-mind** [comment]
@borisblizzard Is the android support of theoraplayer ready for prime-time yet?

**Comment by borisblizzard** [comment]
Almost . :) The theora and theoraplayer modules are almost done and with in a special environment setup already, but still need to be finished as far as a generic setup goes so they can easily be included in any Android Studio project. I'll finish that today and setup the Android Studio project for most or all demos so they can be compiled and deployed easily.

**Comment by borisblizzard** [comment]
Actually we won't be able to have the demos up quickly, because we didn't have Android demos before either. But all 4 relevant modules (theoraplayer, theora, ogg, tremor) now have a working Android Studio setup. Include the module directory "android-studio/lib" in your Android Studio project to use them. Even though there is no demo for testing it, there is a dummy setup in "android-studio/targets" in the root and you can take a look at "android-studio/targets/settings.gradle" how the module directories are linked into the Android Studio project. I'm not sure if it will work flawlessly when trying to add them through Android Studio's GUI.

**Comment by machine-mind** [comment]
Hi @borisblizzard I was just wondering if the generic theoraplayer integration for Android is ready. If so I'd be more than happy to test it.

Best,
Stefan
