### ISSUE TITLE
Release and ReleaseS use same directory for builds, Debug and DebugS do too.

### ISSUE THREAD

**Issue by blloyd75** [AprilAndFriends/theoraplayer#9]
For Visual Studio builds:
Both Dynamic and Static builds go to the same directory (either Debug or Release).

Since different parameters are used during the build, this can cause issues if switching from DebugS to Debug and not doing a clean before another build.
Also, the non-static builds do not create the  libvpx.lib to allow usage of libvpx.dll that is created.

**Comment by kspes** [comment]
@borisblizzard what do you think?

**Comment by borisblizzard** [comment]
This is actually the correct behavior due to the way our build outputs are organized. When building a final EXE, usually one goes with either using only static or maximum dynamic linkage (some libraries don't have a dynamic option due to the way their code is organized, one example being libvpx), link input directories can easily be specified and it's easier to mix static and dynamic links if needed. The disadvantage is that after switching targets around it requires a cleanup sometimes.

**Comment by blloyd75** [comment]
Then if Dynamic versions of libvpx are not valid, should that build always use it's DebugS and ReleaseS builds?  It is capable of building a .dll, but the dynamic build for libvpx does not include the link library.

**Comment by borisblizzard** [comment]
Due to some preprocessors that propagate through all libraries and are used in headers, the Release and Debug are for linking with DLLs, vut they also put out static libs. Hm, I'll see if I can rethink the process. Since there actually problems with mixing DLLs and static libs.

**Comment by borisblizzard** [comment]
Alright, I changed some things regarding output directories. Now binary output are the same as the intermediate directories and then the files are manually copied into the lib/dll directory from before so linking is made simpler. Switching build configurations from dynamic to static and vice versa does not require any special cleanup anymore.

**Comment by blloyd75** [comment]
Sorry for the delay, but after testing this from a clean build, I get the following two errors building for visual studio 2013.
Basically, `

**Comment by borisblizzard** [comment]
Hm, I messed up with the config. These two should always compile as static, even for "dynamic build configurations". Anyway, it's fixed.
